baseUrl: /
languageCode: en-us
theme: terminal
paginate: 5

params:
  contentTypeName: posts
  themeColor: blue
  showMenuItems: 3
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: false
  autoCover: true
  readingTime: true
  enableEmoji: true
  enableInlineShortcodes: true

languages:
  en:
    languageName: English
    title: codeslikeaduck
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
    missingContentMessage: "Content Missing"

    params:
      logo:
        logoText: codeslikeaduck
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about
